# Generated by Django 4.2.3 on 2023-08-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_rename_menu_menuitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="inventory",
            field=models.SmallIntegerField(),
        ),
    ]
